// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJpqzA4qfAYtIDQBJh-_v4O3n4Uslmfg',
    appId: '1:899248746686:web:2fdc53bf75eaad1ad2aeef',
    messagingSenderId: '899248746686',
    projectId: 'message-app-a96ab',
    authDomain: 'message-app-a96ab.firebaseapp.com',
    storageBucket: 'message-app-a96ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6thkZBI3yAbcFJ8qUm5264rbVmMG9w_A',
    appId: '1:899248746686:android:190074642d16f2f7d2aeef',
    messagingSenderId: '899248746686',
    projectId: 'message-app-a96ab',
    storageBucket: 'message-app-a96ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASQkAB_ogpzg7fWqBGMdhCy_DZaIoDOno',
    appId: '1:899248746686:ios:d21b8f4f1a4315f9d2aeef',
    messagingSenderId: '899248746686',
    projectId: 'message-app-a96ab',
    storageBucket: 'message-app-a96ab.appspot.com',
    iosClientId: '899248746686-v3h8upknu8d0phs11k3f8i4tbdu2h78f.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageApp',
  );
}
